spring.profiles.active=local
spring.application.name=spring-strategy-demo

logging.level.root=INFO
logging.level.org.springframework.web=INFO
logging.level.com.erebelo.springstrategydemo=INFO

server.servlet.contextPath=/spring-strategy-demo

# Actuator endpoint
management.endpoints.access.default=none
management.endpoint.health.access=read_only

# MongoDB connection settings
spring.mongodb.uri=mongodb://localhost:27017/strategy_db?replicaSet=rs0